INSERT INTO users (FirstName, LastName, Email, Password, ConnectionID) VALUES ("Roger", "Doger", "roger@doger.com", "rogerdoger", "");
INSERT INTO users (FirstName, LastName, Email, Password, ConnectionID) VALUES ("Super", "Duper", "super@duper.com", "superduper", "");
INSERT INTO users (FirstName, LastName, Email, Password, ConnectionID) VALUES ("First", "Last", "first@last.com", "firstlast", "");

INSERT INTO quizes (Name, Description) VALUES ("Compatibility", "This quiz gagues everything from activities you like to do with a significatnt other, to personal preferences of how you'd behave in common social situations." );
INSERT INTO questions (QuestionString, Qnum, AnswerA, AnswerB, AnswerC, AnswerD, QuizID) VALUES ("If you came upon some free time, which activity would you rather engage in with your partner?", "q1", "Relax at home, eat and watch movies", "An outdoor activity - something new and exciting", "Have sex", "Talk politics", 1);
INSERT INTO questions (QuestionString, Qnum, AnswerA, AnswerB, AnswerC, AnswerD, QuizID) VALUES ("What is the most romantic thing you can do for your partner(if you had no money!)?", "q2", "Tell them you love them and that they are the only one your eyes can see", "Buy them a nice gift", "Be there for them and support them", "Sing to them", 1);
INSERT INTO questions (QuestionString, Qnum, AnswerA, AnswerB, AnswerC, AnswerD, QuizID) VALUES ("On a scale of 1-10, how would you rate your sex life?", "q3", "9-10", "6-8", "3-5", "0-2", 1);
INSERT INTO questions (QuestionString, Qnum, AnswerA, AnswerB, AnswerC, AnswerD, QuizID) VALUES ("Are there things about your sex life that you would like to change that you haven't told your partner about?", "q4", "Some", "None", "A lot", "Your Mom", 1);
INSERT INTO questions (QuestionString, Qnum, AnswerA, AnswerB, AnswerC, AnswerD, QuizID) VALUES ("How soon would you like to get married?", "q5", "More than 5 years/I'm not sure", "Within 5 years", "Within 2 years", "I'm already married", 1);
INSERT INTO questions (QuestionString, Qnum, AnswerA, AnswerB, AnswerC, AnswerD, QuizID) VALUES ("When looking for a partner, how important is age difference?", "q6", "Very important, I'm looking for somebody within 3 years of my age.", "Somewhat important, a 4-7 year difference is right in my wheelhouse.", "Not super important, 8-15 years difference is totally cool.", "Not at all important, as long as we have chemistry.", 1);
INSERT INTO questions (QuestionString, Qnum, AnswerA, AnswerB, AnswerC, AnswerD, QuizID) VALUES ("Of the following, which best describes an ideal Friday night with your partner?", "q7", "Staying at home and watching a movie together.", "Prefunking at home or a friend's house, then meeting up at the club to dance like nobody's watching.", "Grabbing dinner at a restaurant then seeing a movie or a show.", "I need my alone time and I'm burnt out, I'm playing video games and my partner can find their own thing tonight.", 1);
INSERT INTO questions (QuestionString, Qnum, AnswerA, AnswerB, AnswerC, AnswerD, QuizID) VALUES ("If you were a pirate, what would your trademark accessory be?", "q8", "Hook hand - One human hand is good enough, but I want a built in weapon/ tool for carrying things that might otherwise be tough for a person with two regular old hands.  Also I want to use it to zip-line across the ship.", "Peg leg - My feet get wet on the deck of the ship, this way I have one less foot to be potentially uncomfortable.  Plus, the sound it makes is super intimidating to my foes.", "Glass eye - I'm a bit of a prankster and scaring children is one of my favorite pastimes.", "Parrot on shoulder - I really like having a companion around at all times to bounce ideas off of and have run simple tasks, and I don't mind the mess it leaves all over my coat.", 1);
INSERT INTO questions (QuestionString, Qnum, AnswerA, AnswerB, AnswerC, AnswerD, QuizID) VALUES ("Which Disney Princess best represents  you?", "q9", "Jasmine - I may seem glamorous on the outside but I'm really just looking for a humble partner who gets along with my cat.", "Belle - I love books and hate jerks.  Family is very important to me and I'm very succeptable to Stockholm Syndrome.", "Elsa - I keep to myself because I'm a danger to others.", "Merida - I'm super outdoorsy, love animals and I'm not afraid to get my hands dirty.", 1);
INSERT INTO questions (QuestionString, Qnum, AnswerA, AnswerB, AnswerC, AnswerD, QuizID) VALUES ("When you see couples making out in public, what is your most likely reaction?", "q10", "'Aww, cute!  Nothing gross or inappropriate about that!'", "It depends on the situation, sometimes you just get caught up in the moment.", "It's trashy, that kind of thing should be done only at home.", "I love it, my relationships thrive only when others are watching.", 1);
INSERT INTO questions (QuestionString, Qnum, AnswerA, AnswerB, AnswerC, AnswerD, QuizID) VALUES ("What is your ideal pet?", "q11", "I'm a dog person - they're loyal, fun, and energetic.", "I'm a cat person - they require very little maintenance, they aren't super clingy like dogs, and I'm a little emotionally distant so if I die first I understand if my cat doesn't really care.", "I'm a reptile person - because hey, I'm a bit of a weirdo and I don't care who knows it.", "I'm a fish person - they are low maintenance, relaxing, unobtrusive, and an aquarium makes any room instantly better.", 1);
INSERT INTO questions (QuestionString, Qnum, AnswerA, AnswerB, AnswerC, AnswerD, QuizID) VALUES ("Which of the following best describes your ideal vacation with a partner?", "q12", "Relaxing on a beach, drinking Mai Tais and baking in the sun.", "Backpacking through the wilderness and eating meals around the campfire.", "Visiting an old, historical city with lots of culture and knowledge to absorb.", "Going somewhere with an active nightlife - I like to party.", 1);
INSERT INTO questions (QuestionString, Qnum, AnswerA, AnswerB, AnswerC, AnswerD, QuizID) VALUES ("How socially active are you?", "q13", "I have lots of friends that I see regularly, I'm a social butterfly.", "I have a decent sized circle of friends that I see a few of maybe a couple times a week.", "I have a small set of close friends.  I may not see them often but I can always count on them.", "Friendship makes you weak.  My partner is pretty much my only friend.", 1);
INSERT INTO questions (QuestionString, Qnum, AnswerA, AnswerB, AnswerC, AnswerD, QuizID) VALUES ("If you see a spider on the floor of your house, how would you handle the situation?", "q14", "Squish it - this is MY house.", "Shriek and ask somebody else to squish it.", "Get a cup and capture the spider inside, then release it outside the house.", "Ignore it.  I am at one with all creatures.  Unless it crawls on me, then one of us has to die.", 1);
INSERT INTO questions (QuestionString, Qnum, AnswerA, AnswerB, AnswerC, AnswerD, QuizID) VALUES ("You're out to eat with your partner.  They didn't order fries, but they reach over and take some of yours and eat them without saying a word.  What is your reaction?", "q15", "You confront them - that is theft, and you are appalled they'd presume they can just steal something you were about to eat yourself.", "You don't say anything because that is totally normal.", "You contemplate taking something off their plate that you know they'd want in retaliation, but you decide against it - store the incident in memory to bring up in later arguments.", "Raise hell in the restaurant.  They crossed a line and everybody should know it.", 1);

INSERT INTO quiz_results (ResultString, UserID, QuizID) VALUES ("ABCDABCDABCDABC", 1, 1);
INSERT INTO quiz_results (ResultString, UserID, QuizID) VALUES ("AABBCCDDAABBCCD", 2, 1);
INSERT INTO quiz_results (ResultString, UserID, QuizID) VALUES ("DDDDCCCCBBBBAAA", 3, 1);
